### PR TITLE
refactor(view-{compiler,factory}): use Element.prototype.classList

### PR DESCRIPTION
**Pull request by Gheoan**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I would need to have @jdanyow perf-test this. I'm a little worried about whether it would degrade a critical code path or not. It's looks nice though :)

**Comment by Gheoan** [comment]
Definetly. Another competitor would be `element.className`.

**Comment by jdanyow** [comment]
@Gheoan here's a gist you can use to compare setAttribute, classList and className: https://gist.run/?id=72ba5c3588d6375fee052fc8358a4606

**Comment by Gheoan** [comment]
Here is a comparison: https://gist.run/?id=c6f0af8bb63c695cf0ca2b3eacdab6e4&sha=040748f3bf785efc1e2a6714bd5a51dc832215a5.

I believe repaint performance should be tested too.

**Comment by EisenbergEffect** [comment]
@jdanyow Where are we at with this? Do we need to make changes or keep the code the same?

**Comment by EisenbergEffect** [comment]
It seems like classList is the fastest.

**Comment by jdanyow** [comment]
here's what I got for results (lenovo thinkpad x1 carbon touch):

Chrome
```
running...
setAttribute x 481,968 ops/sec ±1.39% (61 runs sampled)
classList x 406,667 ops/sec ±0.34% (57 runs sampled)
className x 517,682 ops/sec ±0.58% (66 runs sampled)
Fastest is: className
```

Firefox
```
running...
setAttribute x 151,167 ops/sec ±3.36% (56 runs sampled)
classList x 166,265 ops/sec ±0.53% (66 runs sampled)
className x 173,773 ops/sec ±0.77% (64 runs sampled)
Fastest is: className
```

@Gheoan / @EisenbergEffect what did you guys see for results?

**Comment by EisenbergEffect** [comment]
Chrome, Windows on MacBook Pro

running...
setAttribute x 518,528 ops/sec ±2.79% (64 runs sampled)
classList x 573,305 ops/sec ±1.21% (65 runs sampled)
className x 599,219 ops/sec ±4.57% (44 runs sampled)
Fastest is: className

**Comment by EisenbergEffect** [comment]
I think in my comment above, I meant to say `className`. I'll check again on OSX a bit later.

**Comment by jdanyow** [comment]
re-tested using `"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\chrome\dev-sessions\perf" --enable-precise-memory-info --enable-benchmarking --js-flags="--expose-gc"`

```
running...
setAttribute x 472,026 ops/sec ±1.23% (88 runs sampled)
classList x 411,906 ops/sec ±0.42% (93 runs sampled)
className x 532,113 ops/sec ±0.48% (90 runs sampled)
Fastest is: className
```

**Comment by Gheoan** [comment]
Chrome

running...
setAttribute x 144,812 ops/sec ±0.37% (61 runs sampled)
classList x 149,181 ops/sec ±0.87% (64 runs sampled)
className x 152,250 ops/sec ±0.50% (61 runs sampled)
Fastest is: className

Firefox

running...
setAttribute x 74,137 ops/sec ±0.88% (61 runs sampled)
classList x 75,124 ops/sec ±0.96% (62 runs sampled)
className x 78,946 ops/sec ±1.22% (60 runs sampled)
Fastest is: className

`className` seems faster, however I am still in favor of `classList`. Using `classList` prevents same class from being added multiple times and checking if the element already has a class is not needed.

**Comment by Gheoan** [comment]
Also, it would be interesting to see how paint is affected in a benchmark such as dbmonster.

**Comment by EisenbergEffect** [comment]
@Gheoan I don't think paint will be affected since this change affects the compile phase which happens only once.

@jdanyow What do you think? Should I make the change to using `className'?

**Comment by jdanyow** [comment]
This PR (classList) results in nicer code. None of the options really stand out in terms of perf. I'm in board with accepting this PR or switching to className.

**Comment by EisenbergEffect** [comment]
I might just switch it to class name. I'd like to ponder it a bit more.

**Comment by EisenbergEffect** [comment]
Closing this for now. I think if we make a changes we should probably go with className since it's technically the fastest.

**Pull request closed without merging**
