### PR TITLE
feat: Support for `default property` binding on custom attributes

### PR DESCRIPTION
**Pull request by dkent600**
See templating-binding feature request:  https://github.com/aurelia/templating-binding/issues/56

Requires templating-binding PR:  https://github.com/aurelia/templating-binding/pull/108

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I kind of like the idea of using `primaryProperty` so it's less likely to be confused with `defaultValue`. What do you think? @jdanyow

**Comment by jdanyow** [comment]
Sounds good to me- @dkent600 would you mind renaming defaultProperty and defaultBindable to primaryProperty? Then I'll get this merged. Will need another PR for templating-binding because I merged your original already. Make sure you pull down the latest

**Comment by CasiOo** [comment]
I have a couple questions to the changes made to `config.json`.

Why is `core-js` being taken from version `2.4.1` to `1.2.7`?
Why is `npm:aurelia-templating@1.1.4` suddenly added to `config.json` when it wasn't needed before?

**Comment by dkent600** [comment]
@CasiOo 

`npm:aurelia-templating@1.1.4` was added to the project only for testing purposes.
`core-js@1.2.7` -- I don't know.  I wasn't willing to mess with the version numbers as JSPM left them.

**Comment by CasiOo** [comment]
@dkent600 Ah, because `aurelia-templating` is a dependency of `aurelia-templating-binding`.

The core-js version change still worries me.

**Comment by dkent600** [comment]
@CasiOo I just reverted the core-js version numbers, downloaded the resulting package, built and ran all the tests, successfully.  The change is committed to this PR.

**Comment by dkent600** [comment]
@jdanyow The property changes are commited.

**Comment by CasiOo** [comment]
After this feature gets merged, there should be opened an enhancement task to remove the cyclic dependencies. Having `aurelia-templating-binding` as a dependency for the tests results in a cyclic dependency tree, because `aurelia-templating` will end up with a dependency on itself (the npm version).

Surely we should be able to come up with a test suit where `aurelia-templating-binding` isn't needed.

**Comment by dkent600** [comment]
If anyone wants to enlist me further in this, let me know.

**Pull request merged**
