### PR TITLE
chore(tests): add tests for view slot

### PR DESCRIPTION
**Pull request by PWKad**
Covers all except the content selector methods

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Dude! You are awesome! It's hard to over-state how helpful this! I'll review and get it in shortly.

**Comment by EisenbergEffect** [comment]
I get 26 failed tests...

**Comment by EisenbergEffect** [comment]
Did you do an install of aurelia-pal-browser to dev? And maybe not save it?

**Comment by PWKad** [comment]
Most likely yes one sec

**Comment by EisenbergEffect** [comment]
Hmm. Ok, I will check this out a bit later. Might need to release first then get the tests working LOL

**Comment by EisenbergEffect** [comment]
Yep, 26 failed tests. I'll investigate a bit further and see if I can figure it out.

**Comment by EisenbergEffect** [comment]
Figured it out. Incorrect import of DOM.

**Pull request merged**
