### PR TITLE
Write Templating Basics to resolve #338

### LINKED ISSUE #338: Create Templating Basics Documentation
An issue to track the work on the Templating Basics documentation.

### PR DESCRIPTION
**Pull request by scottmmjackson**
Wrote a document outlining the basics of Aurelia templating, walking the user through writing a custom element in pure markup, adding in the ViewModel, binding behaviours, importing custom elements and binding to custom attributes, conditionals, repeaters, and event binding.

Re: Issue #338

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Wow! I can't wait to read this. @scottmmjackson Thanks for working on this. @AshleyGrant Thanks for overseeing the progress. I'll read through it tonight or tomorrow morning and see about getting this out in the next couple of days. The community is really going to appreciate this!

**Comment by AshleyGrant** [comment]
@scottmmjackson would you mind rebasing this PR in to a single commit that matches our commit message [guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit). Thanks!

**Comment by AshleyGrant** [comment]
@EisenbergEffect we've fixed the commit message issues and smooshed everything in to a single commit.

**Comment by EisenbergEffect** [comment]
Ok, this is a good start. I think the biggest issue with this document is that it duplicates a lot of content that is present in other articles, but doesn't cover all the basics of templating. There's duplication of binding (another article Jeremy is writing) and there's duplication of custom elements. What we want to do here is explain the templating-specific things. Here's a list of topics, in no particular order:

[x] All views as Web Components Templates
[x] Explain String Interpolation
[x] Explain Binding Commands - You don't need to go too deep because it's covered elsewhere.
[x] Explain Delegate vs. Trigger - Need to mention call as well, but don't go too deep because it's being covered in the binding doc.
[x] Explain using repeat with arrays
[ ] Explain using repeat with Map
[ ] Explain using repeat with Set
[ ] Explain repeating with Object keys (including limitations)
[ ] Explain repeating over a number
[x] Explain if
[ ] Explain with
[ ] Explain if, repeat and show are template controllers. Explain that you can use the template tag with a template controller when no wrapping element is present.
[x] Explain show
[ ] Explain hide
[x] Explain Require
[ ] Explain global vs. local resources (show registering a global resource)
[ ] Introduce the view resource pipeline (file extensions and loader plugins can plug into the require element and global resource loading. Don't go too deep. There will be a whole article on this.)
[ ] Mention the css attribute. 
[ ] Explain template debugging with compile-sp, view-spy and aurelia context plugin
[ ] Explain focus
[ ] Introduce compose, don't need to go too deep. There is an article devoted to this planned.

**Comment by scottmmjackson** [comment]
Great! This looks like a comprehensive list. I might need to do a little bit of digging for a couple of subjects, but it's definitely a solid amount of information.

As far as binding and ValueConverters, I knew that they were pushing the scope of the documentation, but I also recognize that they're some of the features that set Aurelia's custom elements apart from other frameworks, and was hoping that I could touch on them rather than going too far in depth. I'm going to see if I can't reduce both of them, bearing in mind that ValueConverters may just not make the cut.

**Comment by EisenbergEffect** [comment]
Don't delete anything for now. If you are able to work on the missing items, we can then do a second pass to decide what needs to be removed. Thanks for being willing to help!

**Comment by scottmmjackson** [comment]
Alright, did some work on the missing items. Here are some items I might require a little bit of gitter explanation on:
```
[ ] Explain if, repeat and show are template controllers. Explain that you can use the template tag with a template controller when no wrapping element is present.
[ ] Explain global vs. local resources (show registering a global resource)
[ ] Introduce the view resource pipeline (file extensions and loader plugins can plug into the require element and global resource loading. Don't go too deep. There will be a whole article on this.)
[ ] Mention the css attribute. 
[ ] Explain template debugging with compile-spy, view-spy and aurelia context plugin
[ ] Explain focus
[ ] Introduce compose, don't need to go too deep. There is an article devoted to this planned.
```

**Comment by AshleyGrant** [comment]
Let's do a zoom session to go through these, @scottmmjackson

**Comment by scottmmjackson** [comment]
The new version is a little lean on a few things. Notably `.call` isn't covered, yet. For one thing, it seems like it's not exactly the same as it was when older documentation was written, so I'm hoping I can hash that out for the next push.

**Comment by EisenbergEffect** [comment]
@scottmmjackson Please see this PR for another small topic to mention in the templating docs: https://github.com/aurelia/framework/pull/421

**Comment by EisenbergEffect** [comment]
@scottmmjackson @AshleyGrant Thanks for all the work on this guys! What's the current status? Is it still a work in progress?

**Comment by scottmmjackson** [comment]
@EisenbergEffect In the last push I incorporated as-element. I think I might still need to address `.call`, which I left out for a while because of the difficulty distinguishing it from a `.delegate/trigger` approach in a way that made sense.

**Comment by EisenbergEffect** [comment]
`.call` allows the consumer to pass a function reference along to the property, which it can "call" at any point it desires in the future.

**Comment by scottmmjackson** [comment]
Added call to the most recent version

**Comment by EisenbergEffect** [comment]
@scottmmjackson Pending a final review, do you feel this is good to merge?

**Comment by scottmmjackson** [comment]
I just did a run through- gonna make a couple of formatting tweaks that shouldn't take more than 20 minutes or so. Once that's done, we should be good to merge.

**Comment by scottmmjackson** [comment]
Just noting, it should be good to merge.

**Comment by EisenbergEffect** [comment]
@jdanyow Should we go ahead and merge this? Or do you want use this as a source document to generate multiple new documents from?

**Comment by scottmmjackson** [comment]
My 2c: it's a pretty large document. I could also submit a version that I think represents the bare bones basics that someone would need to start making templates, and split out the advanced topics into a second document.

**Comment by EisenbergEffect** [comment]
@scottmmjackson FYI We're going to have @jdanyow take a look at this. He was going to write the binding document. We may break this apart and put some content in different places, etc. Thanks for working on it! I just wanted to let you know we hadn't forgotten it and that we were planning to get it in. We just might change the format a bit.

**Comment by scottmmjackson** [comment]
Great! If there's anything I can do to help, just let me know.

**Comment by EisenbergEffect** [comment]
@scottmmjackson I got it merged finally! I'm going to have @niieani and @jdanyow take a deeper look. I think @niieani is interested in contributing on top of this and helping to fill out any missing pieces. We've got some binding docs from @jdanyow going out next week so we'll probably remove a little bit of the duplication.

**Comment by AshleyGrant** [comment]
YEAH!!!

**Pull request merged**
