### PR TITLE
feat(view-compiler): compile empty templates

### LINKED ISSUE #385: empty view template throws TypeError: Cannot read property 'nodeType' of null
I have a custom element with an empty view template 

        <template></template>

.  Work is done in the viewmodel class to build a progress bar.  When I go to a page that includes it (stripped page down to just the require tag) it throws the following error.  This didn't happen in prior version (just updated today to latest via jspm update).  If I add a single space to the file it will work fine.  

aurelia-logging-console.js?bust=1465942700016:54 ERROR [app-router] TypeError: Cannot read property 'nodeType' of null
    at ViewCompiler.compile (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js?bust=1465942700016:2462:21)
    at eval (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js?bust=1465942700016:3109:50)

### PR DESCRIPTION
**Pull request by shanonvl**
- Minor refactoring of unit test spec to include a top-level `ViewCompiler` describe function and a new `compile` describe function which includes the validation test for this fix.

Resolves #385

### CODE REVIEW

**Comment by shanonvl** [comment]
Closing as I no longer need this PR due to `<slot>` implementation.

**Comment by valichek** [comment]
Would be nice to get reopened because of getting back `replaceable` feature

**Comment by valichek** [comment]
Need that fix for following scenario:
```
<template replaceable part="top"></template>
```

**Comment by EisenbergEffect** [comment]
@valichek I can re-open and merge. Can you confirm that the above PR fixes the issue?

**Comment by valichek** [comment]
@EisenbergEffect sure, looking forward for new version

**Comment by valichek** [comment]
@EisenbergEffect I do confirm the PR fixes the issue, checked locally just editing compiled script in /node_modules/

**Comment by EisenbergEffect** [comment]
Great. We'll get it in.

**Pull request merged**
