### PR TITLE
feat(ViewCompiler): enable compiling strings

### PR DESCRIPTION
**Pull request by Alxandr**
Untested. Written in GH editor.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
I wasn't abel to merge this since it was from a while back. However, I did get the fix in. Not sure why this didn't get in earlier. My apologies.

**Comment by lneffa** [comment]
Any background on how to begin using this fix? Just trying to catch up!

**Comment by EisenbergEffect** [comment]
It's not released yet. But basically, the compiler will take a string and return a view factory.

**Comment by lneffa** [comment]
Oh great to check out! Looking forward to the release :) :+1:

**Pull request closed without merging**
