### PR TITLE
feat(animator): add extra animator methods

### PR DESCRIPTION
**Pull request by Aaike**
add extra animator methods for extra functionality and for working with
JS based animators

fixes: https://github.com/aurelia/templating/issues/88

### CODE REVIEW

**Comment by zewa666** [comment]
@EisenbergEffect I've discussed those changes before hand with @Aaike and will also apply the possible changes to the CSS-Animator. As from my side, this one is ok to merge :+1:

**Comment by EisenbergEffect** [comment]
Has this been based solely on velocity? or have we confirmed that this abstraction would also work with something like greensock, for example?

**Comment by Aaike** [comment]
I was going to create a GSAP implementation next ;)

Velocity has the same syntax as jQuery's `$.animate`.
`animate(element,propertiesOrEffectName,options)`

But GSAP is slightly different : `tweenlite.to(element,duration,options)`

However i think velocity's signature allows for more flexibility
The duration is separate in GSAP but this can be extracted from the `options` object.

The idea playing effects by name is done through "labels" in their TimeLine implementation.
The implementation for playing different "effects" would have to be done by creating a timeline for each effect , or to register an effect in one shared timeline.
This value can be the retrieved from the 2nd argument from the velocity/jquery signature.

I had something like this in mind for implementing GSAP with the new functions:
```
class GreensockAnimator{

  effects = {};

  function animate(element,effectName,options){
    if(typeof effectName == "string"){
      if(this.effects[effectName]){
        this.effects[effectName].play();
      }
    }else{
      TweenLite.to(element,options.duration,options)
    }
  }

  function registerEffect(effectName,properties){
    var tl = new TimelineLite();
    tl.to(element,options.duration,options);
    this.effects[effectName] = timeline;
  }
  
  function unregisterEffect(effectName,properties){
    delete this.effects[effectName];
  }
  
}
```

Other than GSAP i would also like to implement [TinyAnimate](https://github.com/branneman/TinyAnimate)
that one has a very different signature but it can be made to work with the same base functions.

The reason i want to implement all three is to let users choose between the perfect balance of features and filesize : 

- GSAP TweenLite (26 kb)
- GSAP TweenMax (104 kb)
- Velocity (35kb)
- TinyAnimate (3.8kb)

**Comment by EisenbergEffect** [comment]
Excellent. Yes, we wanted to have the abstraction for exactly this reason. I can merge this in, since it sounds like you've looked over the various apis. We can fix things up as  you implement the different animators. I don't think it will break anyone since it's only animator implementors that will have to deal with the changes at this point.

**Pull request merged**
